### PR TITLE
Comma-separated patterns for conclusion & state; remove 'all' from `delete_workflow_pattern`; various tweaks

### PR DESCRIPTION
**Pull request by God-damnit-all**
1. `delete_run_by_conclusion_pattern` can now match multiple conclusions by using a comma-separated list
2. `delete_workflow_by_state_pattern` can now match multiple states by using a comma-separated list
3. Removes 'all' from `delete_workflow_pattern` since it's unnecessary and makes it unable to target workflows named 'all'
4. Updates the manual triggered workflow example to include an 'Unsuccessful' option for `delete_run_by_conclusion_pattern`
    a. _uses a ternary expression within its job step parameter to resolve to `action_required,cancelled,failure,skipped`_
5. Various description and formatting tweaks

Originally I was only going to do the first item on the above list, but then I figured I should also apply it to the second item, and then I kept noticing other, smaller things that bothered me.

I organized all the changes by commit the best I could.

### CODE REVIEW

**Comment by kamilsk** [comment]
Hi! Changes related to delete_workflow_pattern breaks compatibility. It requires extra code writing in a case with Options. E.g., https://github.com/withsparkle/service/commit/9310d31a9d1e1115d505bb7d74afd350fdd5040e

Context: https://github.com/withsparkle/service/blob/9310d31a9d1e1115d505bb7d74afd350fdd5040e/.github/workflows/cleanup.runs.yml#L9-L33.

**Comment by zydou** [comment]
can anyone tell me why the following configuration delete all my workflow runs (including cancelled, failure, skipped and success)?

```yml
      - name: Delete runs by conclusion
        uses: Mattraks/delete-workflow-runs@v2.0.5
        with:
          retain_days: 0
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: cancelled
```

BTW, `v2.0.4` works fine.

**Comment by zydou** [comment]
This is a BREAKING CHANGE and should bump the tag to `v3`, because people use `Mattraks/delete-workflow-runs@v2` will lost all history runs. @Mattraks

**Comment by zydou** [comment]
It's really okay, we all make mistakes. Anyway, thanks for your effort to improve this action. 🎉

**Pull request merged**
